# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsesorJuridico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dictamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('campo_procuraduria', models.CharField(max_length=50)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial.AsesorJuridico')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('archivo', models.FileField(blank=True, upload_to=b'')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoExpediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gerencia', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExpedienteJuridico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('key', models.CharField(max_length=100, unique=True)),
                ('documentos', models.ManyToManyField(to='judicial.Documento')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial.EstadoExpediente')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial.AsesorJuridico')),
            ],
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OpinionJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(max_length=50)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial.AsesorJuridico')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial.ExpedienteJuridico')),
            ],
        ),
        migrations.CreateModel(
            name='Providencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, upload_to=b'')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial.ExpedienteJuridico')),
                ('gerencia_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial.Gerencia')),
            ],
        ),
        migrations.AddField(
            model_name='dictamen',
            name='expediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial.ExpedienteJuridico'),
        ),
    ]
