# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judicial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientejuridico',
            name='url',
            field=models.CharField(blank=True, max_length=257, null=True),
        ),
    ]
