# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judicial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providencia',
            name='archivo',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='providencia',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
