# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judicial', '0002_auto_20161102_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
