# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-11 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judicial', '0002_auto_20161110_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesorjuridico',
            name='numero_instancia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gerencia',
            name='numero_instancia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
