# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judicial', '0003_auto_20161103_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='url',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
