# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judicial', '0003_auto_20161106_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamen',
            name='numero_instancia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opinionjuridica',
            name='numero_instancia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='providencia',
            name='numero_instancia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
