# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judicial', '0004_estadoexpediente_numero_instancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictamen',
            name='archivo',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='opinionjuridica',
            name='archivo',
            field=models.FileField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='providencia',
            name='archivo',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
