# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judicial', '0004_auto_20161103_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asesorjuridico',
            options={},
        ),
        migrations.AlterModelManagers(
            name='asesorjuridico',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='password',
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='asesorjuridico',
            name='username',
        ),
        migrations.AlterField(
            model_name='dictamen',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial.AsesorJuridico'),
        ),
        migrations.AlterField(
            model_name='dictamen',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expedientejuridico',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial.AsesorJuridico'),
        ),
        migrations.AlterField(
            model_name='opinionjuridica',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judicial.AsesorJuridico'),
        ),
        migrations.AlterField(
            model_name='opinionjuridica',
            name='fecha_emision',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
